POST {{host}}/iuranWargas HTTP/1.1
Content-Type: application/json

{
  "date": "22 November 2011",
  "amount": 40003,
  "description": "+639171234567",
  "warga_id": 3,
  "iuran_id": 2
}

###
GET {{host}}/iuranWargas/1 HTTP/1.1
Content-Type: application/json
Accept: application/json

###
GET {{host}}/iuranWargas HTTP/1.1
Content-Type: application/json
Accept: application/json

###
PUT {{host}}/iuranWargas/1 HTTP/1.1
Content-Type: application/json

{
  "date": "22 D 2012",
  "amount": 20000,
  "description": "+639171234567"
}

###
DELETE {{host}}/iuranWargas/2 HTTP/1.1
Content-Type: application/json