POST {{host}}/iurans HTTP/1.1
Content-Type: application/json

{
  "name": "Iuran untuk Fasilitas Pos RT 5",
  "description": "Perlu membeli antena untuk menghidupkan TV",
  "min_amount": 20000
}

###
GET {{host}}/iurans/4 HTTP/1.1
Content-Type: application/json
Accept: application/json

###
GET {{host}}/iurans HTTP/1.1
Content-Type: application/json
Accept: application/json

###
GET {{host}}/iurans?with=total HTTP/1.1
Content-Type: application/json
Accept: application/json

###
PUT {{host}}/iurans/3 HTTP/1.1
Content-Type: application/json

{
  "name": "Iuran Kegiatan Pos",
  "description": "Nganu",
  "min_amount": 20000
}

###
DELETE {{host}}/iurans/10 HTTP/1.1